apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogIlRtRjZhRzExZEdScGJqcG5hSEJmVTNSMWFtTlRWbGhQYnpjMGRHUlRTVUZEZG5aRlJuQjVjek54WVVKUE1HOVdaMDlIIgogICAgICAgICAgICAgICAgfQogICAgICAgIH0KfQo=
type: kubernetes.io/dockerconfigjson
