apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJUbUY2YUcxMWRHUnBianBuYUhCZk1tYzVNMWhsT1dsdVZrUlFjR1UzY0dKM01ITldiREF3VUVWak9VUnRNbGRTTkRKMSIKCQl9LAoJCSJnaXR2ZXJzZS5ydSI6IHsKCQkJImF1dGgiOiAiYm1GNmFHMTFkR1JwYmpwVk5uZE1RRXR6ZEVCTk5rQjROSEk9IgoJCX0sCgkJInNwYXJjLXB1YmxpYy5jci5jbG91ZC5ydSI6IHsKCQkJImF1dGgiOiAiTkRGa1ltUmlOVGN4T1dKaU1ESmtNMkkyWW1KaFpEZ3dNbVU0T1daa05UVTZOekkwWVRrd1lUZzJaRE5pTURZMVlqZGhOV1kzTWpoaFpqTmpNamMxWkdFPSIKCQl9LAoJCSJ3ZC1zcGFyYy5jci5jbG91ZC5ydSI6IHsKCQkJImF1dGgiOiAiTkRGa1ltUmlOVGN4T1dKaU1ESmtNMkkyWW1KaFpEZ3dNbVU0T1daa05UVTZOekkwWVRrd1lUZzJaRE5pTURZMVlqZGhOV1kzTWpoaFpqTmpNamMxWkdFPSIKCQl9Cgl9Cn0K
type: kubernetes.io/dockerconfigjson
